apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: apache-container
        image: localhost:32000/apache-1:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 80  # Updated to new port

