apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: flask-container
        image: localhost:32000/flask:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  # Updated to new port

