apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 80  # Updated to new target port
    protocol: TCP
  selector:
    app: demo

